#!/bin/bash
set -e

USER_UID=$(id -u)
USER_GID=$(id -g)

docker run -it --rm \
  --env=USER_UID=$USER_UID \
  --env=USER_GID=$USER_GID \
  --env=DISPLAY=unix$DISPLAY \
  --volume=/tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume=/run/user/$USER_UID/pulse:/run/pulse:ro \
  --volume=$HOME/.docker-volumes/spotifyconfig:/data/config \
  --name spotify \
  spotify
