#!/bin/bash
set -e

if [[ -n "$(docker ps -qaf 'name=spotify')" ]]; then
	docker restart spotify
else
	USER_UID=$(id -u)
	USER_GID=$(id -g)
	xhost "si:localuser:${USER}"

	docker run --rm --name spotify \
		-e "USER_UID=${USER_UID}" \
		-e "USER_GID=${USER_GID}" \
		-e "DISPLAY=unix${DISPLAY}" \
		-v /tmp/.X11-unix:/tmp/.X11-unix:ro \
		-v "/run/user/${USER_UID}/pulse:/run/pulse:ro" \
		-v "${HOME}/.spotify/config:/data/config" \
		-v "${HOME}/.spotify/cache:/data/cache" \
		--device /dev/dri \
		spotify
fi
